version: '3.8'
services:
  service1:
    build:
      context: .
      dockerfile: ./service1/Dockerfile
    container_name: service1
    ports:
      - "8081:8081"
    networks:
      - my-network

  service2:
    build:
      context: .
      dockerfile: ./service2/Dockerfile
    container_name: service2
    ports:
      - "8082:8082"
    networks:
      - my-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - my-network

  jmeter:
    image: justb4/jmeter
    container_name: jmeter
    depends_on:
      - service1
      - service2
    networks:
      - my-network
    volumes:
      - ./jmeter:/testplans
      - ./jmeter-results:/results
    command: [
      "-n",
      "-t", "/testplans/testPlan.jmx",
      "-l", "/results/result.jtl",
      "-e",
      "-o", "/results/report"
    ]

volumes:
  grafana-storage:

networks:
  my-network:
    driver: bridge
