version: '3.8'
services:
  service1:
    build:
      context: .
      dockerfile: ./service1/Dockerfile
    container_name: service1
    ports:
      - "8081:8081"
    networks:
      - my-network

  service2:
    build:
      context: .
      dockerfile: ./service2/Dockerfile
    container_name: service2
    ports:
      - "8082:8082"
    networks:
      - my-network

  service3:
    build:
      context: .
      dockerfile: ./service3/Dockerfile
    container_name: service3
    ports:
      - "8083:8083"
    networks:
      - my-network

  service4:
    build:
      context: .
      dockerfile: ./service4/Dockerfile
    container_name: service4
    ports:
      - "8084:8084"
    networks:
      - my-network

  service5:
    build:
      context: .
      dockerfile: ./service5/Dockerfile
    container_name: service5
    ports:
      - "8085:8085"
    networks:
      - my-network

  service6:
    build:
      context: .
      dockerfile: ./service6/Dockerfile
    container_name: service6
    ports:
      - "8086:8086"
    networks:
      - my-network

  service7:
    build:
      context: .
      dockerfile: ./service7/Dockerfile
    container_name: service7
    ports:
      - "8087:8087"
    networks:
      - my-network

  service8:
    build:
      context: .
      dockerfile: ./service8/Dockerfile
    container_name: service8
    ports:
      - "8088:8088"
    networks:
      - my-network

  service9:
    build:
      context: .
      dockerfile: ./service9/Dockerfile
    container_name: service9
    ports:
      - "8089:8089"
    networks:
      - my-network

  service10:
    build:
      context: .
      dockerfile: ./service10/Dockerfile
    container_name: service10
    ports:
      - "8099:8099"
    networks:
      - my-network


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - my-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - my-network

volumes:
  grafana-storage:

networks:
  my-network:
    driver: bridge
