global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'service1'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['service1:8081']

  - job_name: 'service2'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['service2:8082']

  - job_name: 'service3'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['service3:8083']