global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'service1'
    static_configs:
      - targets: ['service1:8081']  # Nazwa kontenera i port w Docker Compose

  - job_name: 'service2'
    static_configs:
      - targets: ['service2:8082']
