server:
  port: 8083

spring:
  application:
    name: service3

communication:
  strategy: BROADCAST  # Możliwe wartości: LEADER, BROADCAST, ROUND_ROBIN
  nodes:
    - http://service1:8081
    - http://service2:8082

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
