server:
  port: 8082

spring:
  application:
    name: service2

communication:
  strategy: BROADCAST  # Possible values: LEADER, BROADCAST, ROUND_ROBIN
  nodes:
    - http://service1:8081
    - http://service2:8083
    - http://service2:8084
    - http://service2:8085
    - http://service2:8086
    - http://service2:8087
    - http://service2:8088
    - http://service2:8089
    - http://service2:8099
    - http://service2:8101
  leader-address: service1:8081


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    org.springframework.core.env: DEBUG