server:
  port: 8082

communication:
  # Możesz tu ustawić inny strategy jeśli chcesz
  strategy: LEADER
  leader-address: service2:8082
  # addresses: [service1:8081, service3:8083, ...]

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
