server:
  port: 8082

spring:
  application:
    name: service2

communication:
  strategy: BROADCAST  # Possible values: LEADER, BROADCAST, ROUND_ROBIN
  nodes:
    - http://service1:8081
    - http://service3:8083
  leader-address: service1:8081


management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  level:
    org.springframework.core.env: DEBUG